/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  BananaAccountProxy,
  BananaAccountProxyInterface,
} from "../BananaAccountProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_singleton",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
] as const;

const _bytecode =
  "0x6080346100c957601f61015e38819003918201601f19168301916001600160401b038311848410176100ce578084926020946040528339810103126100c957516001600160a01b038116908190036100c957801561007957600080546001600160a01b031916919091179055604051607990816100e58239f35b60405162461bcd60e51b815260206004820152602260248201527f496e76616c69642073696e676c65746f6e20616464726573732070726f766964604482015261195960f21b6064820152608490fd5b600080fd5b634e487b7160e01b600052604160045260246000fdfe6080604052600080546001600160a01b031690803563530ca43760e11b14603c57808092368280378136915af43d82803e156038573d90f35b3d90fd5b6020918152f3fea2646970667358221220062a34c5f2edd6e195c856ae72bda7671b4747eb8dae7220a928b511097ce4f364736f6c634300080f0033";

type BananaAccountProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BananaAccountProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BananaAccountProxy__factory extends ContractFactory {
  constructor(...args: BananaAccountProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _singleton: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BananaAccountProxy> {
    return super.deploy(
      _singleton,
      overrides || {}
    ) as Promise<BananaAccountProxy>;
  }
  override getDeployTransaction(
    _singleton: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_singleton, overrides || {});
  }
  override attach(address: string): BananaAccountProxy {
    return super.attach(address) as BananaAccountProxy;
  }
  override connect(signer: Signer): BananaAccountProxy__factory {
    return super.connect(signer) as BananaAccountProxy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BananaAccountProxyInterface {
    return new utils.Interface(_abi) as BananaAccountProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BananaAccountProxy {
    return new Contract(address, _abi, signerOrProvider) as BananaAccountProxy;
  }
}
