/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Migration, MigrationInterface } from "../Migration";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "targetSingleton",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "singleton",
        type: "address",
      },
    ],
    name: "ChangedMasterCopy",
    type: "event",
  },
  {
    inputs: [],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "migrationSingleton",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "safe120Singleton",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60c0346100d957601f61035938819003918201601f19168301916001600160401b038311848410176100de578084926020946040528339810103126100d957516001600160a01b0381168082036100d957156100895760a0523060805260405161026490816100f58239608051818181605e01526101ff015260a051818181608601526101bc0152f35b60405162461bcd60e51b815260206004820152602260248201527f496e76616c69642073696e676c65746f6e20616464726573732070726f766964604482015261195960f21b6064820152608490fd5b600080fd5b634e487b7160e01b600052604160045260246000fdfe60806040818152600436101561001457600080fd5b600091823560e01c9081632e773185146101eb5750806389f54308146101a857638fd3ab801461004357600080fd5b346101a457816003193601126101a4576001600160a01b03307f0000000000000000000000000000000000000000000000000000000000000000821614610147577f0000000000000000000000000000000000000000000000000000000000000000168060018060a01b0319845416178355815190602082017f035aff83d86937d35b32e04f0ddc6ff469290eef2f1b692d8a815c89404d474981523084840152838352606083019280841067ffffffffffffffff8511176101335783855251902060065581527f75e41bc35ff1bf14d81d1d2f649c0084a0f974f9289c803ec9898eeec4c8d0b890602090a151f35b634e487b7160e01b86526041600452602486fd5b815162461bcd60e51b815260206004820152603060248201527f4d6967726174696f6e2073686f756c64206f6e6c792062652063616c6c65642060448201526f1d9a584819195b1959d85d1958d85b1b60821b6064820152608490fd5b5080fd5b50346101a457816003193601126101a457517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b8390346101a457816003193601126101a4577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f3fea26469706673582212200f706b3a94f536fcd2226c5db0d4678b6ac31ba57f9566d040445196969ec2db64736f6c634300080f0033";

type MigrationConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MigrationConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Migration__factory extends ContractFactory {
  constructor(...args: MigrationConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    targetSingleton: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Migration> {
    return super.deploy(targetSingleton, overrides || {}) as Promise<Migration>;
  }
  override getDeployTransaction(
    targetSingleton: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(targetSingleton, overrides || {});
  }
  override attach(address: string): Migration {
    return super.attach(address) as Migration;
  }
  override connect(signer: Signer): Migration__factory {
    return super.connect(signer) as Migration__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MigrationInterface {
    return new utils.Interface(_abi) as MigrationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Migration {
    return new Contract(address, _abi, signerOrProvider) as Migration;
  }
}
